# Generated by Django 3.1.3 on 2020-11-08 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20201108_0339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='xray',
            field=models.FileField(upload_to='xrays/'),
        ),
    ]
